config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :flats
  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  before_action :set_flat, only: [:show, :edit, :update, :destroy]

  def index
    @flats = Flat.all
  end

  def show
  end

  def new
    @flat = Flat.new
  end

  def create
    @flat = Flat.new(flat_params)
    @flat.save
    redirect_to flat_path(@flat)
  end

  def edit
  end

  def update
    @flat.update(flat_params)
    redirect_to flat_path(@flat)
  end

  def destroy
    @flat.destroy
    redirect_to flats_path
  end

  private

  def set_flat
    @flat = Flat.find(params[:id])
  end

  def flat_params
    params.require('flat').permit(:name, :address, :description, :price_per_night, :number_of_guests)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/_form.html.erb
<%= simple_form_for flat do |f| %>
<%= f.input :name %>
<%= f.input :address %>
<%= f.input :description %>
<%= f.input :price_per_night %>
<%= f.input :number_of_guests %>
<%= f.submit 'Save flat!' %>
<% end %>

app/views/flats/edit.html.erb
<h1>EDIT A FLAT</h1>
<%= render 'form', flat: @flat %>

app/views/flats/index.html.erb
<nav class="navbar navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand">Simple Airbnb</a>
    <form class="d-flex">
      <button class="btn btn-outline-success"><%= link_to "Add a flat", new_flat_path, style: 'text-decoration: none;' %>
</button>
    </form>
  </div>
</nav>

<div class="container">
<h1>ALL THE FLATS (<%= @flats.count %>)</h1>
  <div class="row row-cols-1 row-cols-md-3 g-4">
    <% @flats.each do |flat| %>
     <div class="col">
    <div class="card h-100">
      <img src="https://picsum.photos/200/100" class="card-img-top" alt="...">
      <div class="card-body">
        <h5 class="card-title"><%= flat.name  %></h5>
        <p class="card-text"><%= flat.address %></p>
        <span class="guests">
          <i class="fas fa-user"></i> <%= flat.number_of_guests %>
        </span>
        <span class="price">
          <i class="fas fa-pound-sign"></i> <%= flat.price_per_night %>
        </span>
      </div>
      <div class="card-footer">
      <%# A remplacer par des link to %>
        <%= link_to "More infos", flat_path(flat) %>
        <%= link_to "Edit", edit_flat_path(flat), class: 'text-warning' %>
        <%= link_to "Remove", flat_path(flat), data: {turbo_method: :delete, turbo_confirm: "Confirm?"}, class: 'text-danger'%>
      </div>
    </div>
  </div>
    <% end %>
  </div>
</div>

app/views/flats/new.html.erb
<h1>ADD A FLAT</h1>
<%= render 'form', flat: @flat %>

app/views/flats/show.html.erb
<h1> <%= @flat.name %></h1>
<h1> <%= @flat.address %></h1>
<p><%= @flat.description %></p>
<h2> <%= @flat.number_of_guests %></h2>
<h2> <%= @flat.price_per_night %></h2>

<%= link_to "Return to list", flats_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v6.1.2/css/all.css">
  </head>

  <body>
    <%= yield %>
  </body>
</html>